### ISSUE TITLE
Lovelace plugin / Great Job

### ISSUE THREAD

**Issue by sybux** [Burningstone91/smart-home-setup#1]
Hi Mr. Burningstone91,

first of all, what a great job. 1st time I found a so well documented step-by-step way to implement all stack of HA. I just rebuild all my configuration based on your experience.
Nevertheless, I'm facing a problem with your lovelace configuration. As you have made a very tiny configuration.yaml with including all your configuration in sub files in packages, how to you define ressources for lovelace to include all javascript extension ?
in my previous configuration, I was using something like this :

resources:
  - url: /local/vertical-stack-in-card.js?v=0.3.2
    type: js

but where did you define this in your actual configuration ?

Thanks for feedback.

**Comment by Burningstone91** [comment]
Hi

Thanks a lot for your feedback, highly appreciated!There's a lot more coming if you take a look at my [KanBan Board](https://github.com/Burningstone91/smart-home-setup/projects/1) :)

I use [HACS](https://hacs.xyz/) to install the custom cards and then add the resources through the UI. Any time you install a card through hacs, it will give you the URL to the card. Then you go to 'Configuration' -> 'Lovelace Dashboards'. Then at the top go to 'Resources', press the orange plus button at the bottom right corner and paste the URL.

**Comment by sybux** [comment]
I've found the option just before your reply. It's working perfectly also in that way :) I've seen your kanban great job. I'm using ZigBee2MQTT as zigbee operator. Just installed with docker it's working like a charm !
