### ISSUE TITLE
Instead of deConz to zha

### ISSUE THREAD

**Issue by europer** [Burningstone91/smart-home-setup#10]
Hi, great explanation the part how to install on a pi the conbee 2 what is not on the same computer as the HA is running and I could successfully do the same. My HA server is in the basement and my pi with the conbee in the living room. But this was a test. My real system use a sonoff tasmota ZigBee with zha but I'm not happy with the sonoff so I want to try out conbee but would like to use the zha instead of deConz integration but same setup as now. HA server in basement, pi with conbee in living room but integrated into the zha. Do you know how to do this? If direct in the same server as HA it findes the path for the zha must use for the conbee but since we are using on pc for HA and another for conbee it's not so easy. Every help would be appreciated. Thanks in advance, Per

**Comment by Burningstone91** [comment]
There are some options to do this, but this depends on your installation method, as far as I know with Home Assistant OS it's pretty difficult to do. 

There's a thread about this in the forums -> https://community.home-assistant.io/t/rpi-as-z-wave-zigbee-over-ip-server-for-hass/23006

You can also search for ser2net on google.

**Comment by europer** [comment]
Thanks for the reply 😊 I will check your link
