### ISSUE TITLE
[question] bed occupancy

### ISSUE THREAD

**Issue by sunsgs** [Burningstone91/smart-home-setup#2]
Where did u put the foil papers? Underneath the bed sheets or in the bottom part between the mattress it self and the slats?

**Comment by Burningstone91** [comment]
Between the mattress and the slats, but I'm going to refine it in the near future as I have to adjust it every 2-3 weeks currently.

**Comment by sunsgs** [comment]
How are U going to do it?

**Comment by Burningstone91** [comment]
I still need to think about it, it's no priority at the moment.
I put it in my backlog -> https://github.com/Burningstone91/smart-home-setup/projects/1#card-51831393
I'll close this issue.
